version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: fix_previleges.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: root
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: root
