version: 0.0
os: linux
files:
  - source: ./demo-0.0.1-SNAPSHOT.jar
    destination: /tmp'


version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ec2-user
  ValidateService:
    - location: scripts/server_validate.sh
      timeout: 60
      runas: ec2-user
BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
    - location: create_or_update_service.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: root
